# Generated by Django 3.2.19 on 2023-10-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='TechStore/frontend/public/img/'),
        ),
    ]
